version: '3.3'
services:
  app:
    container_name: fitnestrackingapp
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      # - ~/.m2:/root/.m2
      - ./.m2:/root/.m2
    environment:
      - GRIDDB_NOTIFICATION_MEMBER=db:10001
      - GRIDDB_CLUSTER_NAME=dockerGridDB
      - GRIDDB_USER=admin
      - GRIDDB_PASSWORD=admin
      - spring.thymeleaf.prefix=file:src/main/resources/templates/
    command: sh ./docker-entrypoint-dev.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    networks:
      - fitnestracking-net
    depends_on:
      - db
  db:
    container_name: fitnestrackingdb
    build:
      context: ./griddbdocker
      dockerfile: Dockerfile55
    volumes:
      - fitnestracking-vol:/var/lib/gridstore
    ports:
      - 10001:10001
      - 20001:20001
    networks:
      - fitnestracking-net

networks:
  fitnestracking-net:
volumes:
  fitnestracking-vol: